// <auto-generated />
using System;
using CargoWorld.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CargoWorld.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20191104183516_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CargoWorld.Models.Car", b =>
                {
                    b.Property<int>("IdCar")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdDriver")
                        .HasColumnType("int");

                    b.HasKey("IdCar");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("CargoWorld.Models.Cargo", b =>
                {
                    b.Property<int>("Id_Cargo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.HasKey("Id_Cargo");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("CargoWorld.Models.CargoInCar", b =>
                {
                    b.Property<int>("Id_Delivery")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AmountOfCarog")
                        .HasColumnType("int");

                    b.Property<int?>("Id_CarIdCar")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Cargo1")
                        .HasColumnType("int");

                    b.HasKey("Id_Delivery");

                    b.HasIndex("Id_CarIdCar");

                    b.HasIndex("Id_Cargo1");

                    b.ToTable("CargoInCars");
                });

            modelBuilder.Entity("CargoWorld.Models.Group", b =>
                {
                    b.Property<int>("IdGroup")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CarIdCar")
                        .HasColumnType("int");

                    b.HasKey("IdGroup");

                    b.HasIndex("CarIdCar");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("CargoWorld.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CargoId_Cargo")
                        .HasColumnType("int");

                    b.Property<int?>("GroupIdGroup")
                        .HasColumnType("int");

                    b.HasKey("IdUser");

                    b.HasIndex("CargoId_Cargo");

                    b.HasIndex("GroupIdGroup");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CargoWorld.Models.CargoInCar", b =>
                {
                    b.HasOne("CargoWorld.Models.Car", "Id_Car")
                        .WithMany()
                        .HasForeignKey("Id_CarIdCar");

                    b.HasOne("CargoWorld.Models.Cargo", "Id_Cargo")
                        .WithMany()
                        .HasForeignKey("Id_Cargo1");
                });

            modelBuilder.Entity("CargoWorld.Models.Group", b =>
                {
                    b.HasOne("CargoWorld.Models.Car", null)
                        .WithMany("IdGroup")
                        .HasForeignKey("CarIdCar");
                });

            modelBuilder.Entity("CargoWorld.Models.User", b =>
                {
                    b.HasOne("CargoWorld.Models.Cargo", null)
                        .WithMany("Id_Owner")
                        .HasForeignKey("CargoId_Cargo");

                    b.HasOne("CargoWorld.Models.Group", null)
                        .WithMany("IdOwner")
                        .HasForeignKey("GroupIdGroup");
                });
#pragma warning restore 612, 618
        }
    }
}
